import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Space_Grotesk } from 'next/font/google'
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Customize as needed
  variable: '--font-space-grotesk',     // Optional: CSS variable for Tailwind
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={spaceGrotesk.className}
      >
        <div className='bg-white'>
        {children}
        </div>
      </body>
    </html>
  );
}
