import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Space_Grotesk } from 'next/font/google'
import "./globals.css";
import LayoutWrapper from "./components/LayoutWrapper";
import TokenDebugger from "./components/DebugAuth";
import RedirectDebugger from "./components/DebugAuth";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={spaceGrotesk.className}
      >
        <div className='bg-white'>
          <LayoutWrapper>
          <RedirectDebugger/>
        {children}
        </LayoutWrapper>
        </div>
      </body>
    </html>
  );
}
